In [12]:
import pandas as pd
import numpy as np

In [13]:

url = "/kaggle/input/datasets/shashk99/off-words/sold_test.csv"

data1 = pd.read_csv(url)
 

data1.head()

,post_id,text,tokens,rationales,label
0,995411387894542336,තේ නෙවෙයි තෝ බීලා ඉන්නෙ ගිනි වතුර,තේ නෙවෙයි තෝ බීලා ඉන්නෙ ගිනි වතුර,[],NOT
1,1128238706303864832,@USER තුනක් ඕනේ නෑ එකක් ගැහුවනම් ඇති ලංකාවට ආප...,@USER තුනක් ඕනේ නෑ එකක් ගැහුවනම් ඇති ලංකාවට ආප...,[],NOT
2,1290554471714496514,"@USER , @USER @USER ටහුඩු ඒකි තනියම ජීවත් වෙ...","@USER , @USER @USER ටහුඩු ඒකි තනියම ජීවත් වෙන්...",[],NOT
3,909459929446182913,@USER මර්විනුත් මුද්දරයක් වෙයිද දන්නේ නැ,@USER මර්විනුත් මුද්දරයක් වෙයිද දන්නේ නැ,[],NOT
4,1305480579375198208,@USER ගොසිප් පීපල් නෙමේ හුත්තො. තෝ වගේ හොරෙක්ට...,@USER ගොසිප් පීපල් නෙමේ හුත්තො . තෝ වගේ හොරෙක්...,"[0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]",OFF

In [14]:

url2 = "/kaggle/input/datasets/shashk99/off-words/sold_train.csv"

data2 = pd.read_csv(url2)

data2.head()

,post_id,text,tokens,rationales,label
0,726758237668659201,@USER @USER පට්ට පට පට...,@USER @USER පට්ට පට පට . . .,[],NOT
1,915618589855617026,පරණ කෑල්ල අද වෙනකම් හිටියනම් අදට අවුරුදු 4යි. ...,පරණ කෑල්ල අද වෙනකම් හිටියනම් අදට අවුරුදු 4යි ....,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",OFF
2,925001070430040065,යාළුවා කියලා හිතන් සර් ගේ ඔලුවට රෙද්ද දාලා නෙල...,යාළුවා කියලා හිතන් සර් ගේ ඔලුවට රෙද්ද දාලා නෙල...,[],NOT
3,1397219745707986955,හොඳ මිතුරියක් කතා කලා. විස්තර කතාකරමින් ඉදලා ම...,හොඳ මිතුරියක් කතා කලා . විස්තර කතාකරමින් ඉදලා ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",OFF
4,950376113150222336,"ඔය බනින්නෙ.. හරකා, මී හරකා කිය කිය...","ඔය බනින්නෙ . . හරකා , මී හරකා කිය කිය . . .","[0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0]",OFF

# merge data

In [15]:

# Merge the two datasets
merged_data = pd.concat([data1, data2], ignore_index=True)

# Remove duplicate rows
merged_data = merged_data.drop_duplicates()

# Check result
print("Total rows after merge:", len(merged_data))

# Save to CSV (optional)
merged_data.to_csv("merged_dataset.csv", index=False)

Total rows after merge: 10000